# Generated by Django 2.2.10 on 2020-06-29 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200629_0948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('-id',), 'verbose_name': 'Машина', 'verbose_name_plural': 'Машины'},
        ),
    ]
