# Generated by Django 2.2.10 on 2020-06-17 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200617_1227'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article_Tag_Relation',
            new_name='Article_By_Tag_Relation',
        ),
    ]
